### ISSUE TITLE
Reload Config Fail

### ISSUE THREAD

**Issue by Apathy94** [hope140/Clash#2]
先把网络设置为全局翻墙，可以载入配置之后，还是会报
<img width="262" alt="Screen Shot 2022-01-10 at 00 16 37" src="https://user-images.githubusercontent.com/25723005/148690878-33411530-903f-43a3-8806-ddfe35274bc4.png">
错

**Comment by hope140** [comment]
你可以尝试在浏览器中打开这个[链接](https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Privacy/Privacy_Domain.yaml)，如果正常出现了规则，那你可能需要再排查下你获取规则是否走了代理。当然也有最后的办法，你可以手动下载出现问题的文件放到对应的文件夹中。

**Comment by hope140** [comment]
我把所有的规则全部加上了镜像，你可以再试试

**Comment by Apathy94** [comment]
浏览器中能够正常出现规则，大佬，我把代理都关了，然后在浏览器中打开https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.yaml能够正常出现连接，但是在clash中就是不行啊？

**Comment by hope140** [comment]
其实按照你的报错来看，是你的https访问出现了问题，所以我加上了镜像，镜像之后也是不行吗

**Comment by Apathy94** [comment]
> 其实按照你的报错来看，是你的https访问出现了问题，所以我加上了镜像，镜像之后也是不行吗

抱歉，没看到这条信息，按照大佬你的的方法，可以解决我的问题了，谢谢

**Comment by hope140** [comment]
解决了就好

**Comment by Apathy94** [comment]
谢谢
