### ISSUE TITLE
Reload Config Fail

### ISSUE THREAD

**Issue by Apathy94** [hope140/Clash#3]
大佬，我网络直连在浏览器中可以直接打开链接，但是ClashX却无法下载，错误显示如下
<img width="267" alt="Screen Shot 2022-01-13 at 02 19 12" src="https://user-images.githubusercontent.com/25723005/149198942-ce6af938-76e0-48c1-9856-2f7af68fce2d.png">
<img width="264" alt="Screen Shot 2022-01-13 at 02 22 29" src="https://user-images.githubusercontent.com/25723005/149199426-1aa52993-2caa-40b2-aaf7-c331913b7dff.png">

不知道大佬有没有遇到过这样的问题

**Comment by hope140** [comment]
我说了我加了镜像了呀，你重新fork一遍，或者在https://raw.githubusercontent.com前面加上https://ghproxy.com/
然后你再试试

**Comment by hope140** [comment]
因为配置更新时是不走代理的，所以想要排除有那么一些难，所以镜像这个方法比较简单适用，你先试试吧

**Comment by Apathy94** [comment]
好的，谢谢大佬，我之前没弄明白，这下明白了，谢谢
